---
- hosts: all
  connection: ssh
  gather_facts: false
  become: true
  become_user: ubuntu
  become_method: sudo
  tasks:
    - name: Clone repo
      git:
        repo: git@github.com:matmignin/skylight.git
        dest: ~/skylight
        update: yes

#- name: Deploy React App Front-end Build
#  connection: ssh
#  gather_facts: false
#  hosts: all
#  #become: yes
#  vars:
#    repo_folder: /home/ubuntu/
#    live_folder: /home/git/
#    repo_name: matmignin/skylight
#  tasks:
#    - git:
#        repo: ssh://git@github.com/{{ repo_name }}.git
#        dest: "{{ repo_folder }}"
#        update: yes   

#    - name: Install dependencies
#       yarn:
#        path: "{{ repo_folder }}"   

#    - name: Build project
#      command: yarn build
#      args:
#        chdir: "{{ repo_folder }}"

#    - name: Copy build to live directory
#      command: cp -TRv build {{ live_folder }}
#      args:
#        chdir: "{{ repo_folder }}"
