---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Clone repo
      git:
        repo: git@github.com:matmignin/skylight.git
        dest: /home/ubuntu/skylight
        accept_hostkey: yes

    - name: pip install requirements.txt
      pip:
        requirements: /home/ubuntu/skylight/requirements.txt
        virtualenv: /home/ubuntu/skylight_env
        virtualenv_command: python3 -m venv
        virtualenv_site_packages: no
        #virtualenv_python: python3

    #- name: copy systemd config file
      #copy: 
        #src: /home/ubuntu/skylight/ansible/skylight.service
        #dest: /etc/systemd/skylight.service
        
    - name: Installs Nginx web server
      become: yes
      become_method: sudo
      apt: 
        pkg: nginx 
        state: present 
        update_cache: true
      notify:
        - start nginx

    - name: copy nginx config file
      become: yes
      copy: 
        src: nginx.conf 
        dest: /etc/nginx/sites-available/default

    - name: enable config
      file: 
        dest: /etc/nginx/sites-enabled/default
        src: /etc/nginx/sites-available/default
        state: link  

    - name: Upload default index.html for host
      become: yes
      copy: 
        src: ../webapp/templates/index.html 
        dest: /usr/share/nginx/html/index.html 
        mode: 0644

    - name: Upload assets file
      become: yes
      copy: 
        src: ../webapp/static
        dest: /usr/share/nginx/html/ 
        mode: 0644

    #- name: Create a directory called images
      #file: 
        #path: /usr/share/nginx/html/images 
        #state: directory 
        #mode: 0755

    - name: restart nginx
      become: yes
      become_method: sudo
      service: 
        name: nginx 
        state: restarted

  handlers:
    #- name: start gunicorn
      #service:
        #name: gunicorn
        #state: started

    - name: start Nginx
      service:
        name: nginx 
        state: started
