---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Clone repo
      git:
        repo: https://github.com/matmignin/skylight.git
        dest: /home/ubuntu/skylight
        accept_hostkey: yes

    - name: pip install requirements.txt
      pip:
        requirements: /home/ubuntu/skylight/requirements.txt
        virtualenv: /home/ubuntu/skylight_env
        virtualenv_command: python3 -m venv
        virtualenv_site_packages: no
        #virtualenv_python: python3

    #- name: Create a directory called images
      #file: 
        #path: /usr/share/nginx/html/images 
        #state: directory 
        #mode: 0755
        #
        
    - name: Installs Nginx web server
      apt: 
        pkg: nginx 
        state: present 
        update_cache: true
      notify:
        - start Nginx

    - name: copy nginx config file
      copy: 
        src: nginx.conf 
        dest: /etc/nginx/sites-available/default

    - name: enable config
      file: 
        dest: /etc/nginx/sites-enabled/default
        src: /etc/nginx/sites-available/default
        state: link  

    - name: Upload default index.html for host
      copy: 
        src: ../webapp/templates 
        dest: /usr/share/nginx/html 
        mode: 0644

    #- name: Upload assets file
      #copy: 
        #src: ../webapp/static
        #dest: /usr/share/nginx/html/ 
        #mode: 0644
        #
    - name: restart nginx
      service: 
        name: nginx 
        state: restarted

    #- name: Create a directory called images
      #file: 
        #path: /usr/share/nginx/html/images 
        #state: directory 
        #mode: 0755


  handlers:
    - name: start Nginx
      service:
        name: nginx 
        state: started
